Screen:
    ScreenManager:
        id:scr_mngr
        MainMenuScreen:
            name:"menu"
        InputScreen:
            name:"input"
        RestingHeartRateScreen:
            name:"heartrate"
        ResultObeseScreen:
            name:"obese"
        ResultUnderweightScreen:
            name:"underweight"
        ResultOverweightScreen:
            name:"overweight"
        ResultNormalScreen:
            name:"normal"
        LocationSearchScreen:
            name:"locsearch"
        LocationResultScreen:
            name:"locresult"
        HistoryScreen:
            name:"history"

<MainMenuScreen>
#    MDBoxLayout:
#        ScreenManager:
#            Screen:
    MDBoxLayout:
        orientation:'vertical'
        # MDToolbar:
        #     title:'MD 24/7'
        #     elevation:10

        NewsLayout:
            id: nl  # and in id to access the instance
            pos_hint:{'center_y':0.3}
            orientation:'vertical'

        MDBottomAppBar:
            MDToolbar:
                icon: "account"
                type: "bottom"
                elevation_normal: 8
                on_action_button:
                    root.manager.current='input'
                    root.manager.transition.direction = "right"
                left_action_items:[["history",lambda x: app.history_screen("history")]]
                right_action_items:[["google-earth",lambda x: app.location_screen("locsearch")]]

<NewsLayout>:
    orientation: 'vertical'
    padding: dp(20)
    Label:
        text: root.title
        text_size: self.size
        halign: 'center'
        valign: 'center'
        color : 0,0,0,1
        size_hint_y: None
        height: dp(50)
        bold: True
    AsyncImage:
        source: root.picture
        size_hint_y: .5
    Label:
        text_size: self.size
        halign: 'center'
        text: root.description
        color: 0,0,0,1
        size_hint_y: .8

<InputScreen>
    on_pre_enter: app.clear_inputs()
    id:information
	BoxLayout:
        orientation: 'vertical'
        MDToolbar:
            title:'Input Details'
            elevation:10
            left_action_items:[["backspace",lambda x:app.back_screen("menu")]]
            right_action_items:[["head-question",lambda x:app.info2dialog()]]

        Widget:
        MDTextField:
            id:fname
            hint_text: "Full name"
            icon_right:"account"
            pos_hint: {'center_x': 0.5}
            size_hint_x: None
            width: '250dp'
            helper_text:"Please enter your Registered Name"
            helper_text_mode:"persistent"
        Widget:
            height: dp(35)

        MDTextField:
            id:height
            input_filter:'int'
            hint_text: "Height"
            icon_right:"human-male-height"
            pos_hint: {'center_x': 0.5}
            size_hint_x: None
            width: '250dp'
            helper_text:"Must be in centimeters"
            helper_text_mode:"persistent"
        Widget:
            height:dp(35)

        MDTextField:
            id:weight
            hint_text: "Weight"
            input_filter:'int'
            icon_right:"weight-kilogram"
            pos_hint: {'center_x': 0.5}
            size_hint_x: None
            width: '250dp'
            helper_text:"Must be in Kilogram"
            helper_text_mode:"persistent"
        Widget:
            height:dp(35)

        MDTextField:
            id:age
            hint_text: "Age"
            input_filter:'int'
            icon_right:"cake"
            pos_hint: {'center_x': 0.5}
            size_hint_x: None
            width: '250dp'
            helper_text:"please enter your age"
            helper_text_mode:"persistent"
        Widget:
            height: dp(35)

        MDTextField:
            id:heartrate
            hint_text: "Heartrate"
            input_filter:'int'
            icon_right:"heart-pulse"
            pos_hint: {'center_x': 0.5}
            size_hint_x: None
            width: '250dp'
            helper_text:"Count the beat on your palm for 60 seconds"
            helper_text_mode:"persistent"
        Widget:
            size_hint_y: None

        MDScreen:
            MDRectangleFlatButton:
                mode: "rectangle"
                text: '[color=#000000]Confirm'
                pos_hint: {'center_x':0.5, 'center_y':0.8}
                on_press :
                    app.show_data()

        Widget:
            size_hint_x: None

<ResultObeseScreen>
    BoxLayout:
        orientation: 'vertical'
        MDToolbar:
            title:'Result: OBESE'
            elevation:10
            right_action_items:[["head-question",lambda x:app.result_dialog()]]
        Widget:

        MDLabel:
            text: "People with obesity have increased risk of cardiovascular disease,type 2 diabetes, high blood pressure, and other health conditions. Waist-to-hip ratio, waist-to-height ratio, and body fat percentage measurements can provide a more complete picture of any health risks. A person should consult with their healthcare provider and consider making lifestyle changes through healthy eating and fitness to improve their health indicators. \n TIPS: \n *Change your diet. \n *Consider adding physical activity \n *Consume less “bad” fat and more “good” fat. \n *Eat more servings of vegetables and fruits \n *limit your vices (drinking,smoking,etc)"
            halign: "center"

        Widget:

        MDScreen:
            MDRectangleFlatIconButton:
                icon:"account"
                text: '[color=#000000]Main Menu'
                pos_hint: {'center_x':0.25, 'center_y':0.9}
                on_press : root.manager.current='menu'
            MDRectangleFlatIconButton:
                icon:"heart-pulse"
                text: '[color=#000000]Heartbeat Results'
                pos_hint: {'center_x':0.7, 'center_y':0.9}
                on_press : app.hrdialog()


<ResultNormalScreen>
    BoxLayout:
        orientation: 'vertical'
        MDToolbar:
            title:'Result: NORMAL WEIGHT'
            elevation:10
            right_action_items:[["head-question",lambda x:app.result_dialog()]]
        Widget:

        MDLabel:
            text :"Maintaining a healthy weight may lower the risk of developing certain health conditions, including cardiovascular disease and type 2 diabetes. Waist-to-hip ratio, waist-to-height ratio, and body fat percentage measurements can provide a more complete picture of any health risks. \n TIPS: \n *Limit what you eat \n *exercise \n *sleep 7-8 hours a day \n *maintain a consistent sleeping routine \n *consider eating more healthy foods \n *limit your vices (drinking,smoking,etc)"
            halign: "center"

        Widget:

        MDScreen:
            MDRectangleFlatIconButton:
                icon:"account"
                text: '[color=#000000]Main Menu'
                pos_hint: {'center_x':0.25, 'center_y':0.9}
                on_press : root.manager.current='menu'
            MDRectangleFlatIconButton:
                icon:"heart-pulse"
                text: '[color=#000000]Heartbeat Results'
                pos_hint: {'center_x':0.7, 'center_y':0.9}
                on_press : app.hrdialog()

<ResultOverweightScreen>
    BoxLayout:
        orientation: 'vertical'
        MDToolbar:
            title:'Result: OVERWEIGHT'
            elevation:10
            right_action_items:[["head-question",lambda x:app.result_dialog()]]
        Widget:

        MDLabel:
            text: "Being overweight may increase the risk of certain health conditions, including cardiovascular disease, high blood pressure, and type 2 diabetes. A person should consult with their healthcare provider and consider making lifestyle changes through healthy eating and fitness to improve their health indicators.Being overweight or fat is having more body fat than is optimally healthy \n TIPS: \n *Eat a high protein breakfast. \n *Avoid sugary drinks and fruit juice \n *Drink water before meals. \n *Choose weight-loss-friendly foods. \n *Drink coffee or tea. \n *Base your diet on whole foods. \n *Eat slowly. \n *limit your vices (drinking,smoking,etc)"
            halign: "center"

        Widget:

        MDScreen:
            MDRectangleFlatIconButton:
                icon:"account"
                text: '[color=#000000]Main Menu'
                pos_hint: {'center_x':0.25, 'center_y':0.9}
                on_press : root.manager.current='menu'
            MDRectangleFlatIconButton:
                icon:"heart-pulse"
                text: '[color=#000000]Heartbeat Results'
                pos_hint: {'center_x':0.7, 'center_y':0.9}
                on_press : app.hrdialog()

<ResultUnderweightScreen>
    BoxLayout:
        orientation: 'vertical'
        MDToolbar:
            title:'Result: UNDERWEIGHT'
            elevation:10
            right_action_items:[["head-question",lambda x:app.result_dialog()]]
        Widget:

        MDLabel:
            text: "Being underweight may pose certain health risks, including nutrient deficiencies and hormonal changes. Waist-to-hip ratio, waist-to-height ratio, and body fat percentage measurements can provide a more complete picture of any health risks. A person should consult with their healthcare provider and consider making lifestyle changes through healthy eating and fitness to improve their health indicators.Being underweight can cause health problems. An underweight person is a person whose body weight is considered too low to be healthy \n TIPS: \n *eat more frequently \n *choose nutrient-rich foods \n *watch what you eat and drink \n *exercise \n *limit your vices (drinking,smoking,etc)"
            halign: "center"

        Widget:

        MDScreen:
            MDRectangleFlatIconButton:
                icon:"account"
                text: '[color=#000000]Main Menu'
                pos_hint: {'center_x':0.25, 'center_y':0.9}
                on_press : root.manager.current='menu'
            MDRectangleFlatIconButton:
                icon:"heart-pulse"
                text: '[color=#000000]Heartbeat Results'
                pos_hint: {'center_x':0.7, 'center_y':0.9}
                on_press : app.hrdialog()

<LocationSearchScreen>
    BoxLayout:
        orientation: 'vertical'
        MDToolbar:
            title:'Hospital Searcher'
            elevation:10
            left_action_items:[["backspace",lambda x:app.back_screen6("menu")]]
            right_action_items:[["head-question",lambda x:app.info1_dialog()]]

        ScrollView:
            MDList:
                id: rlist
<RecordLine>:
    adaptive_height: True
    OneLineListItem:
        text: root.text
        on_release: app.showinfo(root.parent.parent.panel_cls.text, self.text)

<InformationDialog>:
    title: "Details:"

<OneLineAvatarIconListItem>:    # The list widget
    id: icnlst
    IconLeftWidget:
        icon: "clipboard"

<HistoryScreen>
    FloatLayout:
        AnchorLayout:
            anchor_x: 'center'
            anchor_y: 'bottom'

    AnchorLayout:
        id: dt_layout

    MDToolbar:
        id: toolbar
        pos_hint: {"top": 1}
        elevation: 6
        title: "Check History"
        left_action_items:[["backspace",lambda x:app.back_screen("menu")]]

    MDScreen:
        MDRectangleFlatIconButton:
            icon: "weight-lifter"
            text: '[color=#000000]Check BMI'
            pos_hint: {'center_x':0.25, 'center_y':0.1}
            on_press : app.bmidialog()
        MDRectangleFlatIconButton:
            icon: "heart-pulse"
            text: '[color=#000000]Heartbeat Results'
            pos_hint: {'center_x':0.7, 'center_y':0.1}
            on_press : app.hrdialog()